// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcTransportRequest.proto

package com.personal.rpc.transport.protocol.protobuf;

public final class RpcTransportRequest {
  private RpcTransportRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Request)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>string className = 2;</code>
     */
    java.lang.String getClassName();
    /**
     * <code>string className = 2;</code>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>string methodName = 3;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>string methodName = 3;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>repeated string argsType = 4;</code>
     */
    java.util.List<java.lang.String>
        getArgsTypeList();
    /**
     * <code>repeated string argsType = 4;</code>
     */
    int getArgsTypeCount();
    /**
     * <code>repeated string argsType = 4;</code>
     */
    java.lang.String getArgsType(int index);
    /**
     * <code>repeated string argsType = 4;</code>
     */
    com.google.protobuf.ByteString
        getArgsTypeBytes(int index);

    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getArgsValueList();
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    com.google.protobuf.Any getArgsValue(int index);
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    int getArgsValueCount();
  }
  /**
   * Protobuf type {@code Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageLite<
          Request, Request.Builder> implements
      // @@protoc_insertion_point(message_implements:Request)
      RequestOrBuilder {
    private Request() {
      uid_ = "";
      className_ = "";
      methodName_ = "";
      argsType_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      argsValue_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private java.lang.String uid_;
    /**
     * <code>string uid = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getUid() {
      return uid_;
    }
    /**
     * <code>string uid = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUidBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(uid_);
    }
    /**
     * <code>string uid = 1;</code>
     */
    private void setUid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uid_ = value;
    }
    /**
     * <code>string uid = 1;</code>
     */
    private void clearUid() {
      
      uid_ = getDefaultInstance().getUid();
    }
    /**
     * <code>string uid = 1;</code>
     */
    private void setUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uid_ = value.toStringUtf8();
    }

    public static final int CLASSNAME_FIELD_NUMBER = 2;
    private java.lang.String className_;
    /**
     * <code>string className = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getClassName() {
      return className_;
    }
    /**
     * <code>string className = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(className_);
    }
    /**
     * <code>string className = 2;</code>
     */
    private void setClassName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      className_ = value;
    }
    /**
     * <code>string className = 2;</code>
     */
    private void clearClassName() {
      
      className_ = getDefaultInstance().getClassName();
    }
    /**
     * <code>string className = 2;</code>
     */
    private void setClassNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      className_ = value.toStringUtf8();
    }

    public static final int METHODNAME_FIELD_NUMBER = 3;
    private java.lang.String methodName_;
    /**
     * <code>string methodName = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getMethodName() {
      return methodName_;
    }
    /**
     * <code>string methodName = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(methodName_);
    }
    /**
     * <code>string methodName = 3;</code>
     */
    private void setMethodName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      methodName_ = value;
    }
    /**
     * <code>string methodName = 3;</code>
     */
    private void clearMethodName() {
      
      methodName_ = getDefaultInstance().getMethodName();
    }
    /**
     * <code>string methodName = 3;</code>
     */
    private void setMethodNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      methodName_ = value.toStringUtf8();
    }

    public static final int ARGSTYPE_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> argsType_;
    /**
     * <code>repeated string argsType = 4;</code>
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getArgsTypeList() {
      return argsType_;
    }
    /**
     * <code>repeated string argsType = 4;</code>
     */
    @java.lang.Override
    public int getArgsTypeCount() {
      return argsType_.size();
    }
    /**
     * <code>repeated string argsType = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getArgsType(int index) {
      return argsType_.get(index);
    }
    /**
     * <code>repeated string argsType = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getArgsTypeBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          argsType_.get(index));
    }
    private void ensureArgsTypeIsMutable() {
      if (!argsType_.isModifiable()) {
        argsType_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(argsType_);
       }
    }
    /**
     * <code>repeated string argsType = 4;</code>
     */
    private void setArgsType(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsTypeIsMutable();
      argsType_.set(index, value);
    }
    /**
     * <code>repeated string argsType = 4;</code>
     */
    private void addArgsType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsTypeIsMutable();
      argsType_.add(value);
    }
    /**
     * <code>repeated string argsType = 4;</code>
     */
    private void addAllArgsType(
        java.lang.Iterable<java.lang.String> values) {
      ensureArgsTypeIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, argsType_);
    }
    /**
     * <code>repeated string argsType = 4;</code>
     */
    private void clearArgsType() {
      argsType_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string argsType = 4;</code>
     */
    private void addArgsTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureArgsTypeIsMutable();
      argsType_.add(value.toStringUtf8());
    }

    public static final int ARGSVALUE_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.Any> argsValue_;
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.Any> getArgsValueList() {
      return argsValue_;
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getArgsValueOrBuilderList() {
      return argsValue_;
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    @java.lang.Override
    public int getArgsValueCount() {
      return argsValue_.size();
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Any getArgsValue(int index) {
      return argsValue_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    public com.google.protobuf.AnyOrBuilder getArgsValueOrBuilder(
        int index) {
      return argsValue_.get(index);
    }
    private void ensureArgsValueIsMutable() {
      if (!argsValue_.isModifiable()) {
        argsValue_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(argsValue_);
       }
    }

    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    private void setArgsValue(
        int index, com.google.protobuf.Any value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureArgsValueIsMutable();
      argsValue_.set(index, value);
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    private void setArgsValue(
        int index, com.google.protobuf.Any.Builder builderForValue) {
      ensureArgsValueIsMutable();
      argsValue_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    private void addArgsValue(com.google.protobuf.Any value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureArgsValueIsMutable();
      argsValue_.add(value);
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    private void addArgsValue(
        int index, com.google.protobuf.Any value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureArgsValueIsMutable();
      argsValue_.add(index, value);
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    private void addArgsValue(
        com.google.protobuf.Any.Builder builderForValue) {
      ensureArgsValueIsMutable();
      argsValue_.add(builderForValue.build());
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    private void addArgsValue(
        int index, com.google.protobuf.Any.Builder builderForValue) {
      ensureArgsValueIsMutable();
      argsValue_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    private void addAllArgsValue(
        java.lang.Iterable<? extends com.google.protobuf.Any> values) {
      ensureArgsValueIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, argsValue_);
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    private void clearArgsValue() {
      argsValue_ = emptyProtobufList();
    }
    /**
     * <code>repeated .google.protobuf.Any argsValue = 5;</code>
     */
    private void removeArgsValue(int index) {
      ensureArgsValueIsMutable();
      argsValue_.remove(index);
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!uid_.isEmpty()) {
        output.writeString(1, getUid());
      }
      if (!className_.isEmpty()) {
        output.writeString(2, getClassName());
      }
      if (!methodName_.isEmpty()) {
        output.writeString(3, getMethodName());
      }
      for (int i = 0; i < argsType_.size(); i++) {
        output.writeString(4, argsType_.get(i));
      }
      for (int i = 0; i < argsValue_.size(); i++) {
        output.writeMessage(5, argsValue_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!uid_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUid());
      }
      if (!className_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getClassName());
      }
      if (!methodName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getMethodName());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < argsType_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(argsType_.get(i));
        }
        size += dataSize;
        size += 1 * getArgsTypeList().size();
      }
      for (int i = 0; i < argsValue_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, argsValue_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request, Builder> implements
        // @@protoc_insertion_point(builder_implements:Request)
        com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.RequestOrBuilder {
      // Construct using com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string uid = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getUid() {
        return instance.getUid();
      }
      /**
       * <code>string uid = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUidBytes() {
        return instance.getUidBytes();
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        copyOnWrite();
        instance.setUid(value);
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder clearUid() {
        copyOnWrite();
        instance.clearUid();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUidBytes(value);
        return this;
      }

      /**
       * <code>string className = 2;</code>
       */
      @java.lang.Override
      public java.lang.String getClassName() {
        return instance.getClassName();
      }
      /**
       * <code>string className = 2;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        return instance.getClassNameBytes();
      }
      /**
       * <code>string className = 2;</code>
       */
      public Builder setClassName(
          java.lang.String value) {
        copyOnWrite();
        instance.setClassName(value);
        return this;
      }
      /**
       * <code>string className = 2;</code>
       */
      public Builder clearClassName() {
        copyOnWrite();
        instance.clearClassName();
        return this;
      }
      /**
       * <code>string className = 2;</code>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassNameBytes(value);
        return this;
      }

      /**
       * <code>string methodName = 3;</code>
       */
      @java.lang.Override
      public java.lang.String getMethodName() {
        return instance.getMethodName();
      }
      /**
       * <code>string methodName = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        return instance.getMethodNameBytes();
      }
      /**
       * <code>string methodName = 3;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        copyOnWrite();
        instance.setMethodName(value);
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       */
      public Builder clearMethodName() {
        copyOnWrite();
        instance.clearMethodName();
        return this;
      }
      /**
       * <code>string methodName = 3;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMethodNameBytes(value);
        return this;
      }

      /**
       * <code>repeated string argsType = 4;</code>
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getArgsTypeList() {
        return java.util.Collections.unmodifiableList(
            instance.getArgsTypeList());
      }
      /**
       * <code>repeated string argsType = 4;</code>
       */
      @java.lang.Override
      public int getArgsTypeCount() {
        return instance.getArgsTypeCount();
      }
      /**
       * <code>repeated string argsType = 4;</code>
       */
      @java.lang.Override
      public java.lang.String getArgsType(int index) {
        return instance.getArgsType(index);
      }
      /**
       * <code>repeated string argsType = 4;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getArgsTypeBytes(int index) {
        return instance.getArgsTypeBytes(index);
      }
      /**
       * <code>repeated string argsType = 4;</code>
       */
      public Builder setArgsType(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setArgsType(index, value);
        return this;
      }
      /**
       * <code>repeated string argsType = 4;</code>
       */
      public Builder addArgsType(
          java.lang.String value) {
        copyOnWrite();
        instance.addArgsType(value);
        return this;
      }
      /**
       * <code>repeated string argsType = 4;</code>
       */
      public Builder addAllArgsType(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllArgsType(values);
        return this;
      }
      /**
       * <code>repeated string argsType = 4;</code>
       */
      public Builder clearArgsType() {
        copyOnWrite();
        instance.clearArgsType();
        return this;
      }
      /**
       * <code>repeated string argsType = 4;</code>
       */
      public Builder addArgsTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addArgsTypeBytes(value);
        return this;
      }

      /**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      @java.lang.Override
      public java.util.List<com.google.protobuf.Any> getArgsValueList() {
        return java.util.Collections.unmodifiableList(
            instance.getArgsValueList());
      }
      /**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      @java.lang.Override
      public int getArgsValueCount() {
        return instance.getArgsValueCount();
      }/**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Any getArgsValue(int index) {
        return instance.getArgsValue(index);
      }
      /**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      public Builder setArgsValue(
          int index, com.google.protobuf.Any value) {
        copyOnWrite();
        instance.setArgsValue(index, value);
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      public Builder setArgsValue(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        copyOnWrite();
        instance.setArgsValue(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      public Builder addArgsValue(com.google.protobuf.Any value) {
        copyOnWrite();
        instance.addArgsValue(value);
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      public Builder addArgsValue(
          int index, com.google.protobuf.Any value) {
        copyOnWrite();
        instance.addArgsValue(index, value);
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      public Builder addArgsValue(
          com.google.protobuf.Any.Builder builderForValue) {
        copyOnWrite();
        instance.addArgsValue(builderForValue);
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      public Builder addArgsValue(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        copyOnWrite();
        instance.addArgsValue(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      public Builder addAllArgsValue(
          java.lang.Iterable<? extends com.google.protobuf.Any> values) {
        copyOnWrite();
        instance.addAllArgsValue(values);
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      public Builder clearArgsValue() {
        copyOnWrite();
        instance.clearArgsValue();
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any argsValue = 5;</code>
       */
      public Builder removeArgsValue(int index) {
        copyOnWrite();
        instance.removeArgsValue(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Request)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          argsType_.makeImmutable();
          argsValue_.makeImmutable();
          return null;
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request other = (com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request) arg1;
          uid_ = visitor.visitString(!uid_.isEmpty(), uid_,
              !other.uid_.isEmpty(), other.uid_);
          className_ = visitor.visitString(!className_.isEmpty(), className_,
              !other.className_.isEmpty(), other.className_);
          methodName_ = visitor.visitString(!methodName_.isEmpty(), methodName_,
              !other.methodName_.isEmpty(), other.methodName_);
          argsType_= visitor.visitList(argsType_, other.argsType_);
          argsValue_= visitor.visitList(argsValue_, other.argsValue_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();

                  uid_ = s;
                  break;
                }
                case 18: {
                  java.lang.String s = input.readStringRequireUtf8();

                  className_ = s;
                  break;
                }
                case 26: {
                  java.lang.String s = input.readStringRequireUtf8();

                  methodName_ = s;
                  break;
                }
                case 34: {
                  java.lang.String s = input.readStringRequireUtf8();
                  if (!argsType_.isModifiable()) {
                    argsType_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(argsType_);
                  }
                  argsType_.add(s);
                  break;
                }
                case 42: {
                  if (!argsValue_.isModifiable()) {
                    argsValue_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(argsValue_);
                  }
                  argsValue_.add(
                      input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
                  break;
                }
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request> parser = PARSER;
          if (parser == null) {
            synchronized (com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Request)
    private static final com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new Request();
    }

    public static com.personal.rpc.transport.protocol.protobuf.RpcTransportRequest.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Request> PARSER;

    public static com.google.protobuf.Parser<Request> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
