// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransportMessage.proto

package com.personal.rpc.transport.protocol.protobuf;

public final class TransportMessage {
  private TransportMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string className = 1;</code>
     */
    boolean hasClassName();
    /**
     * <code>required string className = 1;</code>
     */
    java.lang.String getClassName();
    /**
     * <code>required string className = 1;</code>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>required string methodName = 2;</code>
     */
    boolean hasMethodName();
    /**
     * <code>required string methodName = 2;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>required string methodName = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>repeated string args = 3;</code>
     */
    java.util.List<java.lang.String>
        getArgsList();
    /**
     * <code>repeated string args = 3;</code>
     */
    int getArgsCount();
    /**
     * <code>repeated string args = 3;</code>
     */
    java.lang.String getArgs(int index);
    /**
     * <code>repeated string args = 3;</code>
     */
    com.google.protobuf.ByteString
        getArgsBytes(int index);
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageLite<
          Message, Message.Builder> implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    private Message() {
      className_ = "";
      methodName_ = "";
      args_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    private int bitField0_;
    public static final int CLASSNAME_FIELD_NUMBER = 1;
    private java.lang.String className_;
    /**
     * <code>required string className = 1;</code>
     */
    @java.lang.Override
    public boolean hasClassName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string className = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getClassName() {
      return className_;
    }
    /**
     * <code>required string className = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(className_);
    }
    /**
     * <code>required string className = 1;</code>
     */
    private void setClassName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      className_ = value;
    }
    /**
     * <code>required string className = 1;</code>
     */
    private void clearClassName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      className_ = getDefaultInstance().getClassName();
    }
    /**
     * <code>required string className = 1;</code>
     */
    private void setClassNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      className_ = value.toStringUtf8();
    }

    public static final int METHODNAME_FIELD_NUMBER = 2;
    private java.lang.String methodName_;
    /**
     * <code>required string methodName = 2;</code>
     */
    @java.lang.Override
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string methodName = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getMethodName() {
      return methodName_;
    }
    /**
     * <code>required string methodName = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(methodName_);
    }
    /**
     * <code>required string methodName = 2;</code>
     */
    private void setMethodName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      methodName_ = value;
    }
    /**
     * <code>required string methodName = 2;</code>
     */
    private void clearMethodName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      methodName_ = getDefaultInstance().getMethodName();
    }
    /**
     * <code>required string methodName = 2;</code>
     */
    private void setMethodNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      methodName_ = value.toStringUtf8();
    }

    public static final int ARGS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<java.lang.String> args_;
    /**
     * <code>repeated string args = 3;</code>
     */
    @java.lang.Override
    public java.util.List<java.lang.String> getArgsList() {
      return args_;
    }
    /**
     * <code>repeated string args = 3;</code>
     */
    @java.lang.Override
    public int getArgsCount() {
      return args_.size();
    }
    /**
     * <code>repeated string args = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getArgs(int index) {
      return args_.get(index);
    }
    /**
     * <code>repeated string args = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getArgsBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          args_.get(index));
    }
    private void ensureArgsIsMutable() {
      if (!args_.isModifiable()) {
        args_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(args_);
       }
    }
    /**
     * <code>repeated string args = 3;</code>
     */
    private void setArgs(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
      args_.set(index, value);
    }
    /**
     * <code>repeated string args = 3;</code>
     */
    private void addArgs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
      args_.add(value);
    }
    /**
     * <code>repeated string args = 3;</code>
     */
    private void addAllArgs(
        java.lang.Iterable<java.lang.String> values) {
      ensureArgsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, args_);
    }
    /**
     * <code>repeated string args = 3;</code>
     */
    private void clearArgs() {
      args_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string args = 3;</code>
     */
    private void addArgsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
      args_.add(value.toStringUtf8());
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, getClassName());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeString(2, getMethodName());
      }
      for (int i = 0; i < args_.size(); i++) {
        output.writeString(3, args_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getClassName());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getMethodName());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < args_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(args_.get(i));
        }
        size += dataSize;
        size += 1 * getArgsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message, Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        com.personal.rpc.transport.protocol.protobuf.TransportMessage.MessageOrBuilder {
      // Construct using com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string className = 1;</code>
       */
      @java.lang.Override
      public boolean hasClassName() {
        return instance.hasClassName();
      }
      /**
       * <code>required string className = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getClassName() {
        return instance.getClassName();
      }
      /**
       * <code>required string className = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        return instance.getClassNameBytes();
      }
      /**
       * <code>required string className = 1;</code>
       */
      public Builder setClassName(
          java.lang.String value) {
        copyOnWrite();
        instance.setClassName(value);
        return this;
      }
      /**
       * <code>required string className = 1;</code>
       */
      public Builder clearClassName() {
        copyOnWrite();
        instance.clearClassName();
        return this;
      }
      /**
       * <code>required string className = 1;</code>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClassNameBytes(value);
        return this;
      }

      /**
       * <code>required string methodName = 2;</code>
       */
      @java.lang.Override
      public boolean hasMethodName() {
        return instance.hasMethodName();
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      @java.lang.Override
      public java.lang.String getMethodName() {
        return instance.getMethodName();
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        return instance.getMethodNameBytes();
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        copyOnWrite();
        instance.setMethodName(value);
        return this;
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder clearMethodName() {
        copyOnWrite();
        instance.clearMethodName();
        return this;
      }
      /**
       * <code>required string methodName = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMethodNameBytes(value);
        return this;
      }

      /**
       * <code>repeated string args = 3;</code>
       */
      @java.lang.Override
      public java.util.List<java.lang.String>
          getArgsList() {
        return java.util.Collections.unmodifiableList(
            instance.getArgsList());
      }
      /**
       * <code>repeated string args = 3;</code>
       */
      @java.lang.Override
      public int getArgsCount() {
        return instance.getArgsCount();
      }
      /**
       * <code>repeated string args = 3;</code>
       */
      @java.lang.Override
      public java.lang.String getArgs(int index) {
        return instance.getArgs(index);
      }
      /**
       * <code>repeated string args = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getArgsBytes(int index) {
        return instance.getArgsBytes(index);
      }
      /**
       * <code>repeated string args = 3;</code>
       */
      public Builder setArgs(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setArgs(index, value);
        return this;
      }
      /**
       * <code>repeated string args = 3;</code>
       */
      public Builder addArgs(
          java.lang.String value) {
        copyOnWrite();
        instance.addArgs(value);
        return this;
      }
      /**
       * <code>repeated string args = 3;</code>
       */
      public Builder addAllArgs(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllArgs(values);
        return this;
      }
      /**
       * <code>repeated string args = 3;</code>
       */
      public Builder clearArgs() {
        copyOnWrite();
        instance.clearArgs();
        return this;
      }
      /**
       * <code>repeated string args = 3;</code>
       */
      public Builder addArgsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addArgsBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasClassName()) {
            return null;
          }
          if (!hasMethodName()) {
            return null;
          }
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          args_.makeImmutable();
          return null;
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message other = (com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message) arg1;
          className_ = visitor.visitString(
              hasClassName(), className_,
              other.hasClassName(), other.className_);
          methodName_ = visitor.visitString(
              hasMethodName(), methodName_,
              other.hasMethodName(), other.methodName_);
          args_= visitor.visitList(args_, other.args_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  java.lang.String s = input.readString();
                  bitField0_ |= 0x00000001;
                  className_ = s;
                  break;
                }
                case 18: {
                  java.lang.String s = input.readString();
                  bitField0_ |= 0x00000002;
                  methodName_ = s;
                  break;
                }
                case 26: {
                  java.lang.String s = input.readString();
                  if (!args_.isModifiable()) {
                    args_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(args_);
                  }
                  args_.add(s);
                  break;
                }
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message> parser = PARSER;
          if (parser == null) {
            synchronized (com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Message)
    private static final com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new Message();
    }

    public static com.personal.rpc.transport.protocol.protobuf.TransportMessage.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Message> PARSER;

    public static com.google.protobuf.Parser<Message> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
