// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Result.proto

package com.personal.rpc.demo.model;

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string exception = 3;</code>
   */
  java.lang.String getException();
  /**
   * <code>string exception = 3;</code>
   */
  com.google.protobuf.ByteString
      getExceptionBytes();
}
